package com.pangmaobao.model;

public class Test {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.id
     *
     * @mbggenerated Thu Nov 02 14:53:17 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.test
     *
     * @mbggenerated Thu Nov 02 14:53:17 CST 2017
     */
    private String test;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.id
     *
     * @return the value of test.id
     *
     * @mbggenerated Thu Nov 02 14:53:17 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.id
     *
     * @param id the value for test.id
     *
     * @mbggenerated Thu Nov 02 14:53:17 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.test
     *
     * @return the value of test.test
     *
     * @mbggenerated Thu Nov 02 14:53:17 CST 2017
     */
    public String getTest() {
        return test;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.test
     *
     * @param test the value for test.test
     *
     * @mbggenerated Thu Nov 02 14:53:17 CST 2017
     */
    public void setTest(String test) {
        this.test = test == null ? null : test.trim();
    }
}